=== santimtb/Mate_EBAU/schemas/mate.schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "title": "Examen de Matemáticas",
  "type": "object",
  "required": [
    "comunidad",
    "convocatoria",
    "año",
    "fuente",
    "examen"
  ],
  "properties": {
    "comunidad": {
      "type": "string"
    },
    "convocatoria": {
      "type": "string"
    },
    "año": {
      "type": "integer"
    },
    "fuente": {
      "type": ["string","null"],
      "format": "uri",
      "minLength": 0
    },
    "examen": {
      "type": "array",
      "items": {
        "type": "object",
        "required": [
          "bloque",
          "preguntas"
        ],
        "properties": {
          "bloque": {
            "type": "string",
            "enum": [
              "Álgebra",
              "Geometría Analítica",
              "Análisis",
              "Estadística y Probabilidad"
            ]
          },
          "preguntas": {
            "type": "array",
            "items": {
              "type": "object",
              "required": [
                "numero",
                "puntuacion"
              ],
              "properties": {
                "numero": {
                  "type": "integer"
                },
                "contenido": {
                  "type": "string"
                },
                "imagen": {
                  "type": "string",
                  "pattern": "^$|^https?://.+"
                },
                "temas": {
                  "type": "array",
                  "items": {
                    "type": "string"
                  }
                },
                "dificultad": {
                  "type": "string",
                  "enum": [
                    "baja",
                    "media-baja",
                    "media",
                    "media-alta",
                    "alta"
                  ]
                },
                "puntuacion": {
                  "type": "number"
                },
                "solucion": {
                  "type": "array",
                  "minItems": 0,
                  "items": {
                    "type": "object",
                    "required": [
                      "metodo",
                      "pasos",
                      "resultado"
                    ],
                    "properties": {
                      "metodo": {
                        "type": "string"
                      },
                      "imagen": {
                        "type": "string",
                        "pattern": "^$|^https?://.+"
                      },
                      "pasos": {
                        "type": "array",
                        "items": {
                          "type": "object",
                          "properties": {
                            "contenido": {
                              "type": "string"
                            }
                          }
                        }
                      },
                      "resultado": {
                        "type": "object",
                        "properties": {
                          "contenido": {
                            "type": "string"
                          }
                        }
                      }
                    }
                  }
                },
                "apartados": {
                  "type": "array",
                  "minItems": 0,
                  "items": {
                    "type": "object",
                    "required": [
                      "letra",
                      "contenido",
                      "temas",
                      "dificultad",
                      "solucion",
                      "puntuacion"
                    ],
                    "properties": {
                      "letra": {
                        "type": "string"
                      },
                      "contenido": {
                        "type": "string"
                      },
                      "imagen": {
                        "type": "string",
                        "pattern": "^$|^https?://.+"
                      },
                      "temas": {
                        "type": "array",
                        "items": {
                          "type": "string"
                        }
                      },
                      "dificultad": {
                        "type": "string",
                        "enum": [
                          "baja",
                          "media-baja",
                          "media",
                          "media-alta",
                          "alta"
                        ]
                      },
                      "puntuacion": {
                        "type": "number"
                      },
                      "solucion": {
                        "type": "array",
                        "minItems": 0,
                        "items": {
                          "type": "object",
                          "required": [
                            "metodo",
                            "pasos",
                            "resultado"
                          ],
                          "properties": {
                            "metodo": {
                              "type": "string"
                            },
                            "imagen": {
                              "type": "string",
                              "pattern": "^$|^https?://.+"
                            },
                            "pasos": {
                              "type": "array",
                              "items": {
                                "type": "object",
                                "properties": {
                                  "contenido": {
                                    "type": "string"
                                  }
                                }
                              }
                            },
                            "resultado": {
                              "type": "object",
                              "properties": {
                                "contenido": {
                                  "type": "string"
                                }
                              }
                            }
                          }
                        }
                      }
                    }
                  }
                }
              },
              "allOf": [
                {
                  "if": {
                    "properties": {
                      "apartados": {
                        "type": "array",
                        "minItems": 1
                      }
                    }
                  },
                  "then": {
                    "properties": {
                      "solucion": {
                        "type": "array",
                        "maxItems": 0
                      }
                    }
                  },
                  "else": {
                    "properties": {
                      "solucion": {
                        "type": "array",
                        "minItems": 1
                      }
                    }
                  }
                }
              ]
            }
          }
        }
      }
    }
  }
}

=== santimtb/Mate_EBAU/mate_2/examenes/comunidad_valenciana/2025_junio.json
{
  "$schema": "../../../schemas/mate.schema.json",
  "comunidad": "Comunidad Valenciana",
  "convocatoria": "Junio",
  "año": 2025,
  "fuente": "https://www.ebaumatematicas.com/wp-content/uploads/2025/06/2oBachCC_EBAU_Valencia_2025-Ordinaria.pdf",
  "examen": [
    {
      "bloque": "Estadística y Probabilidad",
      "preguntas": [
        {
          "numero": 1,
          "contenido": "Una pizzería ofrece tres tipos de pizza: margarita, vegetariana y pepperoni. A lo largo de los años, utilizando su aplicación para teléfonos inteligentes, el restaurante ha recopilado datos sobre las preferencias de los clientes, calculando que el 40% de sus clientes piden pizza margarita, el 25% elige la pizza vegetariana y el resto prefiere la pizza pepperoni.",
          "puntuacion": 2.5,
          "temas": ["Probabilidad", "Distribución Binomial"],
          "dificultad": "media-baja",
          "solucion": [],
          "apartados": [
            {
              "letra": "1.1",
              "contenido": "Si se elige un cliente al azar, ¿cuál es la probabilidad de que haya pedido una pizza pepperoni?",
              "imagen": "",
              "temas": ["Probabilidad"],
              "dificultad": "baja",
              "puntuacion": 0.25,
              "solucion": [
                {
                  "metodo": "Sucesos elementales",
                  "imagen": "",
                  "pasos": [
                    {
                      "contenido": "Identificamos los sucesos:<br>M: El cliente pide pizza margarita<br>V: El cliente pide pizza vegetariana<br>P: El cliente pide pizza pepperoni"
                    },
                    {
                      "contenido": "Obtenemos las probabilidades elementales de los sucesos del enunciado: $P(M) = 0.4, P(V) = 0.25$"
                    },
                    {
                      "contenido": "Calculanos la probabilidad de que un cliente pida pizza pepperoni: $$ P(P) = 1 - P(M) - P(V) = 1 - 0.4 - 0.25 = \boxed{\textbf{0.35}}$$ "
                    }
                  ],
                  "resultado": {
                    "contenido": "$$\boxed{\textbf{P(P) = 0.35}}$$"
                  }
                }
              ]
            },
            {
              "letra": "1.2",
              "contenido": "¿Cuál es la probabilidad de que dos clientes elegidos al azar hayan pedido distintos tipos de pizza?",
              "puntuacion": 0.75,
              "temas": [
                "Experimentos aleatorios",
                "Probabilidad",
                "Experimentos compuestos"
              ],
              "dificultad": "baja",
              "imagen": "",
              "solucion": [
                {
                  "metodo": "Diagrama en árbol",
                  "imagen": "https://raw.githubusercontent.com/santimtb/Mate_EBAU/refs/heads/main/mate_2/examenes/comunidad_valenciana/images/2025_Junio_1_2.png",
                  "pasos": [
                    {
                      "contenido": "Planteamos el diagrama en árbol con los sucesos del enunciado",
                      "imagen": "https://raw.githubusercontent.com/santimtb/Mate_EBAU/refs/heads/main/mate_2/examenes/comunidad_valenciana/images/2025_Junio_1_2.png"
                    },
                    {
                      "contenido": "La probabilidad de que dos clientes pidan distintos tipos de pizza es la suma de las probabilidades de los sucesos que cumplen esta condición: $$P(MV) + P(MP) + P(VP) + P(VM) + P(PM) + P(PV)$$ o si usamos los complementarios: $$ 1 - [P(MM) + P(VV) + P(PP)] = 1 - [0.4^2 + 0.25^2 + 0.35^2] = 1 - [0.16 + 0.0625 + 0.1225] = 1 - 0.345 = \boxed{\textbf{0.655}}$$"
                    }
                  ],
                  "resultado": {
                    "contenido": "$$\boxed{\textbf{P('dos clientes pidan distintos tipos de pizza')= 0.655}}$$"
                  }
                }
              ]
            },
            {
              "letra": "1.3",
              "contenido": "Para mejorar su servicio y agilizar los tiempos de preparación, la pizzería decide considerar un grupo típico de 10 clientes con el objetivo de decidir cuántas pizzas margarita preparar con antelación y evitar retrasos durante las horas con más demanda, minimizando el desperdicio.<br><br>¿Cuál es la probabilidad de que exactamente 4 de los 10 clientes pidan pizzas margarita?",
              "puntuacion": 0.75,
              "temas": [
                "Distribución Binomial",
                "Probabilidad"
              ],
              "dificultad": "baja",
              "imagen": "",
              "solucion": [
                {
                  "metodo": "Distribución Binomial",
                  "imagen": "",
                  "pasos": [
                    {
                      "contenido": "Observamos que el enunciado nos da la probabilidad de que un cliente pida pizza margarita: $P(M) = 0.4$ para un total de 10 clientes. Esto nos indica que podemos usar la distribución binomial para calcular la probabilidad de que exactamente 4 de los 10 clientes pidan pizzas margarita.",
                      "imagen": ""
                    },
                    {
                      "contenido": "La distribución binomial quedará definida de la siguiente manera: $\textbf{n}$ es el número de clientes, $\\textbf{p}$ es la probabilidad de éxito (pedir pizza margarita)  y  $\\textbf{q}$ es la probabilidad de fracaso (no pida pizza margarita).<br>En este caso, $n=10, p = 0.4 ~ y ~ q = 1 - p = 0.6$.<br>Siendo $\textbf{X}$ la variable aleatoria que representa el número de clientes que piden pizza margarita, tenemos que: $$X \\sim B(10, 0.4)$$",
                      "imagen": ""
                    },
                    {
                      "contenido": "Para calcular la probabilidad de que exactamente 4 de los 10 clientes pidan pizzas margarita, usamos la fórmula de la distribución binomial: $$P(X = k) = \binom{10}{4} \\cdot p^k \\cdot q^{n-k}$$.",
                      "imagen": ""
                    },
                    {
                      "contenido": "Sustituyendo los valores: $$P(X = 4) = \binom{10}{4} \\cdot (0.4)^4 \\cdot (0.6)^{10-4}$$"
                    },
                    {
                      "contenido": "Calculamos el coeficiente binomial: $$\binom{10}{4} = \frac{10!}{4!(10-4)!} = \frac{10!}{4!6!} = 210$$."
                    },
                    {
                      "contenido": "Sustituyendo en la fórmula: $$P(X = 4) = 210 \\cdot (0.4)^4 \\cdot (0.6)^6$$"
                    },
                    {
                      "contenido": "Calculamos los valores numéricos: $$P(X = 4) = 210 \\cdot 0.0256 \\cdot 0.046656$$"
                    },
                    {
                      "contenido": "Finalmente, calculamos la probabilidad: $$\boxed{\textbf{P(X = 4) = 0.2508}}$$"
                      }
                  ],
                  "resultado": {
                    "contenido": "$$\boxed{\textbf{P(X = 4) = 0.2508}}$$"
                  }
                }
              ]
            },
            {
              "letra": "1.4",
              "contenido": "Para mejorar su servicio y agilizar los tiempos de preparación, la pizzería decide considerar un grupo típico de 10 clientes con el objetivo de decidir cuántas pizzas margarita preparar con antelación y evitar retrasos durante las horas con más demanda, minimizando el desperdicio.<br><br>¿Cuál es la probabilidad de que al menos uno de los 10 clientes del grupo pida una pizza margarita?",
              "puntuacion": 0.75,
              "temas": [
                "Distribución Binomial",
                "Probabilidad"
              ],
              "dificultad": "baja",
              "imagen": "",
              "solucion": [
                {
                  "metodo": "Distribución Binomial Acumulada",
                  "imagen": "",
                  "pasos": [
                    {
                      "contenido": "El cálculo de la probabilidad de que al menos uno de los 10 clientes pida una pizza margarita se puede resolver utilizando la distribución binomial, como en el apartado anterior.",
                      "imagen": ""
                    },
                    {
                      "contenido": "La probabilidad de que al menos 1 cliente pida pizza margarita se puede expresar como: $$P(X \\geq 1) = 1 - P(X < 1) = 1 - P(X=0)$$"
                    },
                    {
                      "contenido": "$$P(X=0)=\binom{10}{0} \\cdot 0.4^0 \\cdot 0.6^{10}=1 \\cdot 1 \\cdot 0.0060$$"
                    },
                    {
                      "contenido": "Por tanto, la probabilidad de que al menos uno de los 10 clientes pida una pizza margarita es: $$P(X \\geq 1) = 1 - P(X=0) = 1 - 0.0060 = \boxed{\textbf{0.9940}}$$"
                    }
                  ],
                  "resultado": {
                    "contenido": "$$\boxed{\textbf{P(X \\geq 1) = 0.9940}}$$"
                  }
                }
              ]
            }
          ]
        }
      ]
    }
  ]
}
